name: build

on:
  push:
    branches:
      - 1.x
    paths:
      - 'src/**'
  schedule:
    - cron: '25 4 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  lsphp-cli:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: cli
      tests: |
        docker run ghcr.io/sitepilot/lsphp-cli:build php -v
        docker run ghcr.io/sitepilot/lsphp-cli:build wp --version
        docker run ghcr.io/sitepilot/lsphp-cli:build composer --version
    secrets: inherit

  lsphp-ols:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: ols
      tests: |
        docker run ghcr.io/sitepilot/lsphp-ols:build /usr/local/lsws/bin/litespeed -v
    secrets: inherit
